### ISSUE TITLE
When you are using a version of Java greater than 8, you have an dataBindingException

### ISSUE THREAD

**Issue by MiguelYann** [konohiroaki/java8-code-kata#14]
To solve this problem, just add these dependencies to your pom.xml

**Comment by MiguelYann** [comment]
` <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.2.11</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>
`

**Comment by konohiroaki** [comment]
I could not reproduce this issue by doing below. I got a successful test result instead.
1. Remove all files under `~/.m2/repository/`
2. `git clone` this repository
3. `cd` to the project directory
4. `git checkout solution`
5. `./mvnw test`

Could you provide more detail so I can reproduce it?

**Comment by MiguelYann** [comment]
It's depend on which version of Java you are using. In fact i'm using Java 11 and when I have cloned the project, and build tests, I have received an exception due to Java 11 don't support javaxdb... Then I have install manualy those missed depnedencies and everything gone OK.

**Comment by konohiroaki** [comment]
Oh I see. I knew for the first time that JAXB was removed in Java 11. Thank you for the catch!
